### ISSUE TITLE
Cannot instantiate printer for default visualizer

### ISSUE THREAD

**Issue by sbobko** [NVIDIA/nsight-vscode-edition#2]
When I try to debug CUDA, I get this message:
![image](https://user-images.githubusercontent.com/46919374/124488422-7e712f80-ddb8-11eb-9a87-7356157973ff.png)
Updating VSCode and reinstalling the extension did not solve the problem.
it is also not possible to view local variables and use other debugging features related to the contents of variables.
Extras:
    "configurations": [
        {
            "name": "CUDA C++: Launch",
            "type": "cuda-gdb",
            "request": "launch",
            "program": "NVIDIA_CUDA-11.3_Samples/bin/x86_64/linux/debug/matrixMul"
        }

**Comment by sbobko** [comment]
@PooyaZv ; @eltonwells 
I tried to solve the problem on my own but apparently it hides deeper than I can find :)

**Comment by eltonwells** [comment]
@sbobko What version of cuda-gdb do you have installed?

**Comment by sbobko** [comment]
@eltonwells Hi, something like this

NVIDIA (R) CUDA Debugger
9.1 release
Portions Copyright (C) 2007-2017 NVIDIA Corporation
GNU gdb (GDB) 7.12
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

**Comment by eltonwells** [comment]
@sbobko CUDA 9.1 is a little old, have you tried a newer version?

Also looking at your screenshot (particularly the call stack view), are you running more than one matrixMul debug session at the same time?

**Comment by sbobko** [comment]
I tried again after I updated everything:
Ubuntu 20.04
NVIDIA_CUDA-11.4
CUDA Debugger 10.1
Fresh launch without prior attempts( to eliminate possible problems)
And nothing has changed. the error is still here...
![image](https://user-images.githubusercontent.com/46919374/127668701-281de243-2df8-4368-b94d-314006cac467.png)


Maybe there are still-any actions or checks that I could do?

**Comment by iosmers** [comment]
hi, I meet the same problem, do you solve it?

**Comment by gmax0** [comment]
A workaround that worked for me:

Install the latest cuda-gdb as mentioned here: https://github.com/NVIDIA/nsight-vscode-edition/issues/8

Within my launch configuration, I set the debugger path to the cuda-gdb bin installed to my conda environment.

```
"debuggerPath": "condapath/cuda-gdb"
```

Relaunched and my variables are now showing.

**Comment by sunlong169** [comment]
I encounter such a problem when using `GDB` other than `CUDA-GDB`. What a surprise!
