### ISSUE TITLE
Launch/Attach with Debugger Args / Environment Vars

### ISSUE THREAD

**Issue by collinmccarthy** [NVIDIA/nsight-vscode-edition#27]
Hello,

With `type=cppdbg` we can configure with [environment](https://code.visualstudio.com/docs/cpp/launch-json-reference#_environment) and [miDebuggerArgs](https://code.visualstudio.com/docs/cpp/launch-json-reference#_midebuggerargs). I would like to do the same when launching and attaching via `type=cuda-gdb`. To use cuda-gdb on our cluster, I need to pass in `--cuda-use-lockfile=0` as a debugger argument and/or set `TMPDIR=${workspaceFolder}/../cuda-gdb` as an environment variable. 

I tried using the following in my `launch.json` but the status bar is missing the current threadblock focus and I'm not sure if it is working 100% correctly under the hood.

```json
// Works, but missing some features, and may have other problems?
{
  "name": "debug",
  "type": "cppdbg",
  "request": "launch",
  "program": "${workspaceFolder}/build-Debug/bin/test",
  "environment": [
    {"name": "TMPDIR", "value": "${workspaceFolder}/../cuda-gdb-tmp"},
  ],
  "MIMode": "gdb",
  "miDebuggerPath": "/usr/local/cuda-11.7/bin/cuda-gdb",
  "miDebuggerArgs": "--cuda-use-lockfile=0",
},
```

Is this the recommended way to do this? Or, is this possible with `type=cuda-gdb` and I'm missing it? If not, please consider it a feature request. I really like debugging in VSCode and don't want to have to resort to the command line tool when I need to use these features. 

Thank you,
-Collin

**Comment by sanannavyaa** [comment]
Hi @collinmccarthy! Currently, we support setting environment variables using envFile. [Here](https://docs.nvidia.com/nsight-visual-studio-code-edition/release-notes/index.html#nsight-vsce-new-2022-1-0) is the documentation. Alternately, you could set `"initCommands" = ["set environment TMPDIR= ${workspaceFolder}/../cuda-gdb-tmp"]` in your launch.json. We currently do not support setting miDebuggerArgs currently, but will consider this is a feature request.

**Comment by sanannavyaa** [comment]
Hi @collinmccarthy as of our [latest release](https://docs.nvidia.com/nsight-visual-studio-code-edition/release-notes/index.html#:~:text=Added%20the%20ability%20to%20set%20environment%20variables%20before%20the%20cuda%2Dgdb%20(or%20cuda%2Dqnx%2Dgdb)%20is%20launched.) we support setting "environment".
