### ISSUE TITLE
How to make STL container readable by editing initcommands?

### ISSUE THREAD

**Issue by qinggengaoshen** [NVIDIA/nsight-vscode-edition#30]
I want to debug code with vscode.But vector always note "-var-list-children Usage:[PRINT_NAME] NAME [FROM_TO].
system:ubuntu 22.10 linux
Here is the launch.json

`
    "version": "0.2.0",
    "configurations": [
        
            "name": "CUDA C++: Launch",
            "type": "cuda-gdb",
            "request": "launch",
            "program": "${workspaceRoot}/lu_cmd",
            "args":["-i /home/tyy/GLU_public-master/src/add32.mtx"],
            "preLaunchTask": "mynvcc",
            "cwd": "${workspaceFolder}",
            "initCommands": [
        
]

**Comment by sanannavyaa** [comment]
Duplicated by discussion in https://github.com/NVIDIA/nsight-vscode-edition/issues/9
