### ISSUE TITLE
[Off-topic?] Nsight compute conda installation broken

### ISSUE THREAD

**Issue by safelix** [NVIDIA/nsight-vscode-edition#42]
Hi there, 

I guess this question is a bit off-topic, but maybe you could forward this internally?

**Problem:** After installing the nsight compute through conda, it doesn't launch with the error message: 
```
ERROR : nsight-compute directory is not found under <conda-path>/../ or /opt/nvidia. Nsight Compute is not installed on your system.
```

**Solution:** The problem seems that the installation directory structure only accounts for the `nsight-compute-<version>` instead of the `nsight-compute/<version>` format. To fix this, I simply added the following code to the `$CUDA_TOOLKIT_BIN_DIR/../ncu` and `$CUDA_TOOLKIT_BIN_DIR/../ncu-ui` bash files on line 47:

```bash
# If installed with cuda, nsight-compute tools will be under nsight-compute/<version> folder. e.g nsight-compute/2019.4.0
for nsight_compute_tool_dir_path in "$CUDA_TOOLKIT_BIN_DIR"/../nsight-compute/*; do
    if [ ! -e "$nsight_compute_tool_dir_path" ]; then
        # Glob didn't match anything. Let's skip this single iteration.
        continue
    fi
    setLatestNsightComputeToolDir "$(basename "$nsight_compute_tool_dir_path")" "$nsight_compute_tool_dir_path"
done
```

The only mention of this issue I found is here: https://github.com/HazyResearch/ThunderKittens/blob/main/docs/conda_setup.md

Best, Felix

**Comment by sanannavyaa** [comment]
For questions related to Nsight compute, please reach out to them via their forum https://forums.developer.nvidia.com/c/developer-tools/nsight-compute/114
