### ISSUE TITLE
Debug specific block/thread

### ISSUE THREAD

**Issue by manurare** [NVIDIA/nsight-vscode-edition#43]
Hello,

I know I am having a `warp illegal address` on `block (20, 15, 0) thread (0, 14, 0)`. However, I am not able to debug at those specific coordinates.

I can debug my cuda kernel OK with VScode nsight extension. I am adding a conditional breakpoint like this inside the kernel but the debugger never stops. What am I doing wrong?

![image](https://github.com/NVIDIA/nsight-vscode-edition/assets/43776720/c534bcd9-f760-47f1-85c3-32a1b39825db)

**Comment by yczhang1028** [comment]
Hi, this conditional breakpoint expression is not valid, there is no syntax like @blockIdx(20, 15, 0).
If you want to stop at that thread, you can use this `CUDA Focus` to switch focus to specific CUDA kernel, and make the break point
Or you can specify blockIdx.x == 20 && blockIdx.y=15 ...., but this might be slow to reach. Prefer to use the first way.
![image](https://github.com/NVIDIA/nsight-vscode-edition/assets/87991152/5e968ab7-093e-4c5f-a026-afebf7709a6d)
![focus_cuda](https://github.com/NVIDIA/nsight-vscode-edition/assets/87991152/c726042b-77bf-4b2f-8ef6-3a636837e4c1)

**Comment by manurare** [comment]
Thank you. Really useful!
