### ISSUE TITLE
How to see cuda Memory View

### ISSUE THREAD

**Issue by weijiel092** [NVIDIA/nsight-vscode-edition#45]
Hi Team,

I want to know whether this extension can see the cuda memory view in vscode. Because I only see the start address of the array, I can't see its memory view.
Or could you provide some method to me? Thanks

![image](https://github.com/NVIDIA/nsight-vscode-edition/assets/171498620/06fc4a39-e9e2-4bb8-a125-b362a7b729cd)

**Comment by veronicajyt** [comment]
Hi, @weijiel092 
You can refer https://docs.nvidia.com/cuda/cuda-gdb/index.html#memory-and-variables to inspect related info.
