### ISSUE TITLE
Set cwd for program when launching the debugger

### ISSUE THREAD

**Issue by mtene** [NVIDIA/nsight-vscode-edition#5]
In VSCode + NSight, I need to be able to configure the path where my program will be launched at. It is important for the application I am debugging and this is possible via the "cwd" launch config property for standard C++ launch configs. The NSight extension does not seem to offer this possibility, although I expect it is easy to add.

**Comment by sanannavyaa** [comment]
Hi @mtene, In 2022, we added the ability for users to be able to specify cwd, [here](https://docs.nvidia.com/nsight-visual-studio-code-edition/release-notes/index.html#nsight-vsce-new-2022-1-0) is the link to the release notes
