### ISSUE TITLE
Debugging on Windows

### ISSUE THREAD

**Issue by mtene** [NVIDIA/nsight-vscode-edition#7]
The extension currently features support for cuda-gdb, but that is not available on Windows. Is there an alternative for pure VSCode + Nsight users (i.e. without Visual Studio)? Can the debugger be packaged as stand-alone and a suitable launch config configured?

**Comment by romanbrickie** [comment]
Met the same issue and anticipate this would work on Windows eventually. Or there is any workaround please explain a bit here.

**Comment by sanannavyaa** [comment]
Hi! Thank you for your feedback. Nsight Visual Studio Code Edition allows you to debug CUDA kernels running on a Linux machine remotely from a Windows machine. However, for debugging kernels running on Windows, NVIDIA offers Nsight Visual Studio Edition, which is our full-featured Windows debugging solution. Thank you!
